version: "3.9"

############################################
#  docker-compose.yml – środowisko RBD
############################################
services:
  # ──────────────────────────────
  # SQL Server #1  (Publisher / główny)
  # ──────────────────────────────
  sql1:
    build:
      context: ./sqlserver          # patrz Dockerfile poniżej
      dockerfile: Dockerfile
    container_name: sql1
    hostname: sql1                  # ułatwia DB-linki
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ng!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"                 # host→container
    volumes:
      - sql1-data:/var/opt/mssql
      - ./init/sql1:/docker-entrypoint-initdb.d
    networks:
      - rbd-net

  # ──────────────────────────────
  # SQL Server #2  (Subscriber / archiwum)
  # ──────────────────────────────
  sql2:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    container_name: sql2
    hostname: sql2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ng!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    volumes:
      - sql2-data:/var/opt/mssql
      - ./init/sql2:/docker-entrypoint-initdb.d
    networks:
      - rbd-net

  # ──────────────────────────────
  # Oracle Database 21c XE
  # (gvenzl/oracle-xe jest legalnym, darmowym
  #  obrazem do celów edukacyjnych)
  # ──────────────────────────────
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    hostname: oracle
    environment:
      - ORACLE_PASSWORD=oracle          # SYS / SYSTEM / APP_USER
      - APP_USER=app
      - APP_USER_PASSWORD=app
    ports:
      - "1521:1521"   # listener
      - "5500:5500"   # APEX / OEM
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init/oracle:/container-entrypoint-initdb.d
    networks:
      - rbd-net

  # ──────────────────────────────
  # PostgreSQL 16  (zamiennik Access/Excel,
  #                 staging dla danych z Mongo)
  # ──────────────────────────────
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    networks:
      - rbd-net

  # ──────────────────────────────
  # MongoDB 6  (e-portfolio, JSON-heavy)
  # ──────────────────────────────
  mongo:
    image: mongo:6
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init/mongo:/docker-entrypoint-initdb.d
    networks:
      - rbd-net

  # ──────────────────────────────
  # pgAdmin 4  – szybki podgląd Postgresa
  # ──────────────────────────────
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - rbd-net

# ──────────────────────────────
# Wspólna sieć i wolumeny
# ──────────────────────────────
networks:
  rbd-net:
    driver: bridge

volumes:
  sql1-data:
  sql2-data:
  oracle-data:
  postgres-data:
  mongo-data:
