version: "3.9"

############################################
#  docker-compose.yml – środowisko RBD
############################################
services:
  # ──────────────────────────────
  # SQL Server #2  (Subscriber / archiwum)
  # ──────────────────────────────
  sql2:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    container_name: sql2
    hostname: sql2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ng!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1434:1433"
    volumes:
      - sql2-data:/var/opt/mssql
      - ./init/sql2:/docker-entrypoint-initdb.d
    networks:
      - rbd-net

  # ──────────────────────────────
  # PostgreSQL 16  
  # ──────────────────────────────
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    networks:
      - rbd-net

  # ──────────────────────────────
  # pgAdmin 4  – szybki podgląd Postgresa
  # ──────────────────────────────
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - rbd-net

# ──────────────────────────────
# Wspólna sieć i wolumeny
# ──────────────────────────────
networks:
  rbd-net:
    driver: bridge

volumes:
  sql2-data:
  postgres-data:
