CREATE USER FINANCE_DB IDENTIFIED BY Finance123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

CREATE USER REMOTE_DB1 IDENTIFIED BY Remote123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

CREATE USER REMOTE_DB2 IDENTIFIED BY Remote123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

ALTER USER FINANCE_DB QUOTA UNLIMITED ON USERS;
ALTER USER REMOTE_DB1 QUOTA UNLIMITED ON USERS;
ALTER USER REMOTE_DB2 QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO FINANCE_DB;
GRANT CONNECT, RESOURCE TO REMOTE_DB1;
GRANT CONNECT, RESOURCE TO REMOTE_DB2;

GRANT CREATE DATABASE LINK TO FINANCE_DB;
GRANT CREATE SYNONYM TO FINANCE_DB;
GRANT CREATE VIEW TO FINANCE_DB;
GRANT CREATE MATERIALIZED VIEW TO FINANCE_DB;
GRANT CREATE SEQUENCE TO FINANCE_DB;
GRANT CREATE TRIGGER TO FINANCE_DB;
GRANT CREATE PROCEDURE TO FINANCE_DB;

GRANT CREATE DATABASE LINK TO REMOTE_DB1;
GRANT CREATE SYNONYM TO REMOTE_DB1;
GRANT CREATE VIEW TO REMOTE_DB1;
GRANT CREATE PROCEDURE TO REMOTE_DB1;

GRANT CREATE DATABASE LINK TO REMOTE_DB2;
GRANT CREATE SYNONYM TO REMOTE_DB2;
GRANT CREATE VIEW TO REMOTE_DB2;
GRANT CREATE PROCEDURE TO REMOTE_DB2;