CREATE SYNONYM remote_contracts FOR REMOTE_DB1.contracts_remote;
CREATE SYNONYM remote_payment_summary FOR REMOTE_DB2.payment_summary;

GRANT SELECT, INSERT, UPDATE, DELETE ON contracts TO REMOTE_DB1;
GRANT SELECT, INSERT, UPDATE, DELETE ON payments TO REMOTE_DB1;
GRANT SELECT, INSERT, UPDATE, DELETE ON contracts TO REMOTE_DB2;
GRANT SELECT, INSERT, UPDATE, DELETE ON payments TO REMOTE_DB2;
